---
boost_weights: subject^2.0 subject_label^1.0 object^2.0 object_label^1.0
description: Associations following OBAN model
display_name: Annotations
document_category: generic_association
fields:
  - description: 'The CURIE for oban:association_has_subject. May be disease, variant, gene, person, ....'
    display_name: Disease
    id: subject
    property: []
    type: string
  - description: 'Label for association_subject. This will always be rdfs:label. Conventions may vary as to what goes in the label. For genes will be symbol, but we may choose to uniquify by prefixing with species'
    display_name: Disease
    id: subject_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: 'Reflexive closure of association_has_subject. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of'
    display_name: Disease
    id: subject_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for subject_closure.
    display_name: Disease
    id: subject_closure_label
    property: []
    searchable: true
    type: string
  - description: Taxonomic class of the subject. This is typically a CURIE of the form NCBITaxon:nnnn.
    display_name: Disease Taxon
    id: subject_taxon
    property: []
    type: string
  - description: Label of taxon.
    display_name: Disease Taxon
    id: subject_taxon_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of taxon. ALWAYS up SubClassOf.
    display_name: Disease Taxon
    id: subject_taxon_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for taxon_closure.
    display_name: Disease Taxon
    id: subject_taxon_closure_label
    property: []
    searchable: true
    type: string
  - description: 'The CURIE for oban:association_has_object. This is often, but not always an ontology class. E.g. for a gene-gene interaction it is an (arbitrary) member of the pair.'
    display_name: Variant
    id: object
    property: []
    type: string
  - description: Label for association_object.
    display_name: Variant
    id: object_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: 'Reflexive closure of association_has_object. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of'
    display_name: Variant
    id: object_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for object_class_closure.
    display_name: Variant
    id: object_closure_label
    property: []
    searchable: true
    type: string
  - description: Taxonomic class of the object. This is typically a CURIE of the form NCBITaxon:nnnn. This field may be unfilled when used with certain categories
    display_name: Variant Taxon
    id: object_taxon
    property: []
    type: string
  - description: Label of taxon.
    display_name: Variant Taxon
    id: object_taxon_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of taxon. ALWAYS up SubClassOf.
    display_name: Variant Taxon
    id: object_taxon_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for taxon_closure.
    display_name: Variant Taxon
    id: object_taxon_closure_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: List of CURIES of all entities that form part of the evidence graph.
    display_name: Evidence
    id: evidence_object
    property: []
    type: string
  - cardinality: multi
    description: evidence object label
    display_name: Evidence
    id: evidence_object_label
    property: []
    type: string
  - cardinality: multi
    description: Closure for evidence object
    display_name: Evidence
    id: evidence_object_closure
    property: []
    type: string
  - cardinality: multi
    description: List of CURIES of all entities that form part of the evidence closure.
    display_name: Evidence
    id: evidence_object_closure_label
    property: []
    type: string
  - description: A unique identifier (CURIE) for the association. Optional.
    display_name: Association id
    id: id
    property: []
    type: uuid
  - description: 'Category of association.subject. Examples: gene, protein, disease, variant'
    display_name: Subject category
    id: subject_category
    property: []
    type: string
  - description: Label for association_subject_category
    display_name: Subject category
    id: subject_category_label
    property: []
    type: string
  - description: A more descriptive label or full name for association_subject. For a gene this may be the full name (as opposed to symbol).
    display_name: Subject description
    id: subject_description
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: synonyms for the entity in the association.subject field.
    display_name: Synonym
    id: subject_synonym
    property: []
    type: string
  - description: Gene related to the subject.
    display_name: Subject Gene
    id: subject_gene
    property: []
    type: string
  - description: Label of the gene.
    display_name: Subject Gene
    id: subject_gene_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of gene.
    display_name: Gene
    id: subject_gene_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for gene_closure.
    display_name: Gene
    id: subject_gene_closure_label
    property: []
    searchable: true
    type: string
  - description: Chromosome related to the subject.
    display_name: Subject Chromosome
    id: subject_chromosome
    property: []
    type: string
  - description: Label of the chromosome.
    display_name: Subject Chromosome
    id: subject_chromosome_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of chromosome.
    display_name: Chromosome
    id: subject_chromosome_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for chromosome_closure.
    display_name: Chromosome
    id: subject_chromosome_closure_label
    property: []
    searchable: true
    type: string
  - description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    id: subject_family
    property: []
    searchable: true
    type: string
  - description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    id: subject_family_label
    property: []
    searchable: true
    type: string
  - description: 'A relationship type that connects the subject with object. TODO: check for correspondence in OBAN'
    display_name: Relationship
    id: relation
    property: []
    type: string
  - description: Label for association_relation
    display_name: Relationship
    id: relation_label
    property: []
    type: string
  - cardinality: multi
    description: SubPropertyOf reflexive closure for association_relation
    display_name: Relationship
    id: relation_closure
    property: []
    type: string
  - cardinality: multi
    description: labels for association_relation_closure
    display_name: Relationship
    id: relation_closure_label
    property: []
    type: string
  - cardinality: multi
    description: 'Association qualifier. TBD: NEGATION should probably be handled differently somehow'
    display_name: Qualifier
    id: qualifier
    property: []
    type: string
  - description: 'Category of association.object. Examples: phenotype, function, process, location, tissue, gene. In GO this is called aspect'
    display_name: Object type
    id: object_category
    property: []
    type: string
  - description: Label for association_object_category
    display_name: Object type
    id: object_category_label
    property: []
    type: string
  - description: Gene related to the subject.
    display_name: Object Gene
    id: object_gene
    property: []
    type: string
  - description: Label of the gene.
    display_name: Object Gene
    id: object_gene_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of gene.
    display_name: Gene
    id: object_gene_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for gene_closure.
    display_name: Gene
    id: object_gene_closure_label
    property: []
    searchable: true
    type: string
  - description: Chromosome related to the subject.
    display_name: Object Chromosome
    id: object_chromosome
    property: []
    type: string
  - description: Label of the chromosome.
    display_name: Object Chromosome
    id: object_chromosome_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Reflexive closure of chromosome.
    display_name: Chromosome
    id: object_chromosome_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for chromosome_closure.
    display_name: Chromosome
    id: object_chromosome_closure_label
    property: []
    searchable: true
    type: string
  - description: 'Assoc object alternate form. E.g. for a canonical protein may be isoforms. Can we generalize this? May be deleted'
    display_name: Isoform
    id: object_isoform
    property: []
    type: string
  - cardinality: multi
    description: 'Reflexive closure of association_has_object. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of'
    display_name: Inferred object
    id: object_class_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for object_class_closure.
    display_name: Involved in
    id: object_class_closure_label
    property: []
    searchable: tru
    type: string
  - cardinality: multi
    description: 'Optional. This is similar to object_class_closure, but allows for the scenario whereby a different (more inclusive, or exclusive) closure is used. The exact OPs used will depend on the association type. This would ideally be communicating from loader conf through to the client somehow'
    display_name: Inferred object
    id: object_class_secondary_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for object_class_secondary_closure.
    display_name: Involved in
    id: object_class_secondary_closure_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Extension class for the annotation.
    display_name: Annotation extension
    id: object_extension
    property: []
    type: string
  - cardinality: multi
    description: Extension class for the annotation.
    display_name: Annotation extension
    id: object_extension_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Extension class for the annotation.
    display_name: Annotation extension
    id: object_extension_closure
    property: []
    type: string
  - cardinality: multi
    description: Extension class for the annotation.
    display_name: Annotation extension
    id: object_extension_closure_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: Extension class for the annotation (JSON).
    display_name: Annotation extension
    id: object_extension_json
    property: []
    type: string
  - cardinality: multi
    description: "TBD: ALIGN GO AND DC TERMINOLOGY. Source of association. The association may be derived from multiple source, but this should be the 'outer' source, if applicable"
    display_name: Source
    id: source
    property: []
    type: string
  - cardinality: multi
    description: Label for source
    display_name: Object
    id: source_label
    property: []
    searchable: true
    type: string
  - cardinality: multi
    description: CURIEs for source_closure
    display_name: Object (Inferred)
    id: source_closure
    property: []
    type: string
  - cardinality: multi
    description: Labels for source_closure
    display_name: Object (Inferred)
    id: source_closure_label
    property: []
    searchable: true
    type: string
  - description: "Date of assignment. The association may be derived from multiple source, but this should be the 'outer' source, if applicable."
    display_name: Date
    id: date
    property: []
    type: string
  - description: "TBD: ALIGN GO AND DC TERMINOLOGY. Source of association. The association may be derived from multiple source, but this should be the 'outer' source, if applicable"
    display_name: Assigned by
    id: assigned_by
    property: []
    type: string
  - description: Rational for redundancy of annotation.
    display_name: Redundant for
    id: is_redundant_for
    property: []
    type: string
  - description: Evidence graph
    display_name: Evidence graph formatted as graphson
    id: evidence_graph
    property: []
    type: string
  - cardinality: multi
    description: Evidence type. In Monarch we may have a graph/chain. This is always the 'outer' evidence OR a list of all evidence types used?
    display_name: Evidence type
    id: evidence
    property: []
    type: string
  - cardinality: multi
    description: Closure for evidence_type. Always SubClassof
    display_name: Evidence label
    id: evidence_label
    property: []
    type: string
  - cardinality: multi
    description: Closure for evidence_type. Always SubClassof
    display_name: Evidence type
    id: evidence_closure
    property: []
    type: string
  - cardinality: multi
    description: List of CURIES of all entities that form part of the evidence graph.
    display_name: Evidence type
    id: evidence_closure_label
    property: []
    type: string
  - cardinality: multi
    description: citation.
    display_name: Reference
    id: citation
    property: []
    type: string
filter_weights: relation_closure_label^6.5 evidence_closure_label^6.0 subject_closure_label^4.5 object_closure_label^4.0 subject_taxon_closure_label^3.5 object_taxon_closure_label^3.0
id: disease_variant
result_weights: subject^7.0 subject_taxon^6.5 relation^6.0  object^5.0 object_taxon^4.2 evidence^4.0 source^3.5
schema_generating: true
weight: 20
